version: '3'

services:
  web:
    # カレントディレクトリでイメージを構築
    build: .
    # /bin/bashでプロセスを継続させてコンテナの正常終了を防ぐ
    command: bash -c "composer install && /bin/bash"
    # カレントディレクトリをコンテナへマウント
    volumes:
      - .:/usr/src/web
    # プロセスを継続させてコンテナの正常終了を防ぐ
    stdin_open: true

# composerを別コンテナで起動することも可能
# この場合my-php-appのcommandは不要
#  composer:
#    image: composer:latest
#    volumes:
#      - .:/usr/src/myapp
#    working_dir: /usr/src/myapp
#    command: install

  db:
    image: mysql:8.0.32
    # コンテナが停止しても自動で再起動する
    restart: always
    # ホストの13306番ポートにコンテナの3306番ポートをフォワード
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    # コンテナ起動時に実行するSQL群をマウント
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
